# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dst <- function(M) {
    .Call('_BLSM_dst', PACKAGE = 'BLSM', M)
}

lpz_dist <- function(Z) {
    .Call('_BLSM_lpz_dist', PACKAGE = 'BLSM', Z)
}

lpY <- function(Y, lpz, alpha, W) {
    .Call('_BLSM_lpY', PACKAGE = 'BLSM', Y, lpz, alpha, W)
}

mlpY <- function(avZ, Y, W) {
    .Call('_BLSM_mlpY', PACKAGE = 'BLSM', avZ, Y, W)
}

lpz_distNODE <- function(Z, node, diag) {
    .Call('_BLSM_lpz_distNODE', PACKAGE = 'BLSM', Z, node, diag)
}

lpYNODE <- function(Y, Z, alpha, node, diag, W) {
    .Call('_BLSM_lpYNODE', PACKAGE = 'BLSM', Y, Z, alpha, node, diag, W)
}

Z_up <- function(Y, Z, W, alpha, zdelta, mu_z, sd_z) {
    .Call('_BLSM_Z_up', PACKAGE = 'BLSM', Y, Z, W, alpha, zdelta, mu_z, sd_z)
}

alpha_up <- function(Y, lpz, W, alpha, adelta, a_a, a_b) {
    .Call('_BLSM_alpha_up', PACKAGE = 'BLSM', Y, lpz, W, alpha, adelta, a_a, a_b)
}

